-- CCS Connect initial Supabase setup
-- Run this in Supabase SQL Editor (new project) before app rollout.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'student' check (role in ('student', 'faculty', 'admin')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  student_id text unique,
  employee_id text unique,
  department text,
  year_section text,
  program text,
  avatar_url text,
  approved_by uuid references public.profiles(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  title text,
  is_group boolean not null default false,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  type text not null default 'announcement',
  target_role text check (target_role in ('student', 'faculty', 'admin')),
  target_user_id uuid references public.profiles(id) on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.campus_locations (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text,
  building_code text,
  latitude double precision,
  longitude double precision,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create trigger trg_conversations_updated_at
before update on public.conversations
for each row execute procedure public.set_updated_at();

create trigger trg_campus_locations_updated_at
before update on public.campus_locations
for each row execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  role_value text;
  id_number_value text;
begin
  role_value := coalesce(new.raw_user_meta_data->>'role', 'student');
  if role_value not in ('student', 'faculty', 'admin') then
    role_value := 'student';
  end if;

  id_number_value := nullif(new.raw_user_meta_data->>'id_number', '');

  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    status,
    department,
    year_section,
    program,
    student_id,
    employee_id
  ) values (
    new.id,
    new.email,
    nullif(coalesce(new.raw_user_meta_data->>'full_name', trim(coalesce(new.raw_user_meta_data->>'first_name', '') || ' ' || coalesce(new.raw_user_meta_data->>'last_name', ''))), ''),
    role_value,
    'pending',
    nullif(new.raw_user_meta_data->>'department', ''),
    nullif(new.raw_user_meta_data->>'year_section', ''),
    nullif(new.raw_user_meta_data->>'program', ''),
    case when role_value = 'student' then id_number_value else null end,
    case when role_value in ('faculty', 'admin') then id_number_value else null end
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    role = excluded.role,
    department = coalesce(excluded.department, public.profiles.department),
    year_section = coalesce(excluded.year_section, public.profiles.year_section),
    program = coalesce(excluded.program, public.profiles.program),
    student_id = coalesce(excluded.student_id, public.profiles.student_id),
    employee_id = coalesce(excluded.employee_id, public.profiles.employee_id),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin(check_user uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = check_user
      and p.role = 'admin'
      and p.status = 'approved'
  );
$$;

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.campus_locations enable row level security;

-- PROFILES
drop policy if exists "profiles_select_self_or_admin" on public.profiles;
create policy "profiles_select_self_or_admin"
on public.profiles
for select
using (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_self_or_admin" on public.profiles;
create policy "profiles_update_self_or_admin"
on public.profiles
for update
using (auth.uid() = id or public.is_admin(auth.uid()))
with check (auth.uid() = id or public.is_admin(auth.uid()));

-- CONVERSATIONS
drop policy if exists "conversations_member_read" on public.conversations;
create policy "conversations_member_read"
on public.conversations
for select
using (
  exists (
    select 1
    from public.conversation_members m
    where m.conversation_id = public.conversations.id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "conversations_create_authenticated" on public.conversations;
create policy "conversations_create_authenticated"
on public.conversations
for insert
with check (auth.uid() = created_by);

drop policy if exists "conversations_update_creator_or_admin" on public.conversations;
create policy "conversations_update_creator_or_admin"
on public.conversations
for update
using (auth.uid() = created_by or public.is_admin(auth.uid()))
with check (auth.uid() = created_by or public.is_admin(auth.uid()));

-- CONVERSATION MEMBERS
drop policy if exists "conversation_members_read_member" on public.conversation_members;
create policy "conversation_members_read_member"
on public.conversation_members
for select
using (
  user_id = auth.uid()
  or exists (
    select 1
    from public.conversation_members me
    where me.conversation_id = public.conversation_members.conversation_id
      and me.user_id = auth.uid()
  )
  or public.is_admin(auth.uid())
);

drop policy if exists "conversation_members_insert_creator_or_admin" on public.conversation_members;
create policy "conversation_members_insert_creator_or_admin"
on public.conversation_members
for insert
with check (
  public.is_admin(auth.uid())
  or exists (
    select 1
    from public.conversations c
    where c.id = public.conversation_members.conversation_id
      and c.created_by = auth.uid()
  )
);

-- MESSAGES
drop policy if exists "messages_read_member" on public.messages;
create policy "messages_read_member"
on public.messages
for select
using (
  exists (
    select 1
    from public.conversation_members m
    where m.conversation_id = public.messages.conversation_id
      and m.user_id = auth.uid()
  )
  or public.is_admin(auth.uid())
);

drop policy if exists "messages_insert_member" on public.messages;
create policy "messages_insert_member"
on public.messages
for insert
with check (
  auth.uid() = sender_id
  and exists (
    select 1
    from public.conversation_members m
    where m.conversation_id = public.messages.conversation_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists "messages_update_sender_or_admin" on public.messages;
create policy "messages_update_sender_or_admin"
on public.messages
for update
using (auth.uid() = sender_id or public.is_admin(auth.uid()))
with check (auth.uid() = sender_id or public.is_admin(auth.uid()));

-- NOTIFICATIONS
drop policy if exists "notifications_read_targeted" on public.notifications;
create policy "notifications_read_targeted"
on public.notifications
for select
using (
  target_user_id is null
  or target_user_id = auth.uid()
  or public.is_admin(auth.uid())
  or (
    target_role is not null
    and exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = public.notifications.target_role
        and p.status = 'approved'
    )
  )
);

drop policy if exists "notifications_insert_admin" on public.notifications;
create policy "notifications_insert_admin"
on public.notifications
for insert
with check (public.is_admin(auth.uid()));

drop policy if exists "notifications_update_admin" on public.notifications;
create policy "notifications_update_admin"
on public.notifications
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- CAMPUS LOCATIONS
drop policy if exists "campus_locations_read_authenticated" on public.campus_locations;
create policy "campus_locations_read_authenticated"
on public.campus_locations
for select
using (auth.uid() is not null);

drop policy if exists "campus_locations_modify_admin" on public.campus_locations;
create policy "campus_locations_modify_admin"
on public.campus_locations
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

-- STORAGE (avatars)
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatars_read_public" on storage.objects;
create policy "avatars_read_public"
on storage.objects
for select
using (bucket_id = 'avatars');

drop policy if exists "avatars_upload_owner" on storage.objects;
create policy "avatars_upload_owner"
on storage.objects
for insert
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = split_part(name, '/', 1)
);

drop policy if exists "avatars_update_owner" on storage.objects;
create policy "avatars_update_owner"
on storage.objects
for update
using (
  bucket_id = 'avatars'
  and auth.uid()::text = split_part(name, '/', 1)
)
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = split_part(name, '/', 1)
);

drop policy if exists "avatars_delete_owner_or_admin" on storage.objects;
create policy "avatars_delete_owner_or_admin"
on storage.objects
for delete
using (
  bucket_id = 'avatars'
  and (
    auth.uid()::text = split_part(name, '/', 1)
    or public.is_admin(auth.uid())
  )
);

-- Realtime tables
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception
  when duplicate_object then null;
end $$;
